### ISSUE TITLE
.NET Core Client

### ISSUE THREAD

**Issue by jkatsiotis** [aldycool/NETCoreSync#3]
Hi,

Any guidance on where to start to build a .NET core client?

**Comment by aldycool** [comment]
Hi @jkatsiotis ,

I assume ".NET Core Client" means that you are using Xamarin, isn't it?

If so, then the synchronization mechanism you should choose is the Xamarin Version of .NET Core Client (because there's also the Flutter version which uses .NET Core backend server. The Flutter version is for clients that is built using Flutter. These all can be read in the root [README.md](https://github.com/aldycool/NETCoreSync#readme)).

For Xamarin, there's an example in the [Samples](https://github.com/aldycool/NETCoreSync/tree/master/Samples) directory, inside it you'll find both of these example that is built using Xamarin technology:

- [DatabaseTimeStamp](https://github.com/aldycool/NETCoreSync/tree/master/Samples/DatabaseTimeStamp) approach
- [GlobalTimeStamp](https://github.com/aldycool/NETCoreSync/tree/master/Samples/GlobalTimeStamp) approach

Their explanation can be read in the [README](https://github.com/aldycool/NETCoreSync/tree/master/NETCoreSync#readme) of the Xamarin version.

**Comment by jkatsiotis** [comment]
I am talking about a .NET core 5.0 client. I have a .NET core 5.0 server and looking to use that. Is is possible to re-use the Xamarin client to achieve that?

Edit: thanks for the swift response

**Comment by aldycool** [comment]
I see...

Well, the Xamarin version is actually only based on netcorestandard2.0, and the dependencies doesn't contain any references to Xamarin whatsoever. You can take a look on the csproj [here](https://github.com/aldycool/NETCoreSync/blob/master/NETCoreSync/NETCoreSync.csproj). So it is usually the clients are using Xamarin because most of them are on mobile platform, but in your case (pure .NET) can also use the library right away.

**Comment by jkatsiotis** [comment]
Thanks
